- name: Set up Raspberry Pi for video streaming
  hosts: raspberry_pi
  become: yes

  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - python3
          - python3-pip
          - libatlas-base-dev
          - libjasper-dev
          - libqtgui4
          - libqt4-test
    
    - name: Install the Python packages
      pip:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - fastapi
          - opencv-python